import * as C from "./promotionalCoreV26.js";

const ROLES=["user","verified_employer_member","org_admin","reviewer","admin","owner"];

function featureChecks(selected=[]){
  return C.FEATURES.map((feature)=>`<label class="promo26-check-card"><input type="checkbox" name="featureIds" value="${C.safe(feature.id)}" ${selected.includes(feature.id)?"checked":""}><span><strong>${C.safe(feature.name)}</strong><small>${C.safe(feature.description)}</small></span></label>`).join("");
}
function roleChecks(selected=ROLES){
  return ROLES.map((role)=>`<label class="promo26-check-card"><input type="checkbox" name="eligibleRoles" value="${C.safe(role)}" ${selected.includes(role)?"checked":""}><span>${C.safe(C.humanize(role))}</span></label>`).join("");
}
function expiryText(record){
  if(record.campaignExpiryBehavior==="revoke_on_campaign_end" && C.timestampMs(record.campaignEndsAt))return `Campaign ends ${C.formatTimestamp(record.campaignEndsAt)}`;
  if(C.timestampMs(record.expiresAt))return `Expires ${C.formatTimestamp(record.expiresAt)}`;
  return "Permanent until revoked";
}

export async function renderAccessHub(){
  C.setTitle("Promotional Access");
  const access=await C.loadAccess(true);
  C.root.innerHTML=`<section class="promo26-access-hero" data-promo-v26-page><p class="eyebrow">Cognitus Promotional Access</p><h1>Unlock more of Cognitus.</h1><p>Promotional codes can grant temporary or permanent access to restricted Cognitus tools without changing your account role or administrative authority.</p><div class="promo26-access-card"><form class="promo26-redeem-inline" data-access-redeem><label>Promotional Code<input name="code" maxlength="40" autocomplete="off" placeholder="COGNITUS2026" required></label><button class="button button-light" type="submit">Redeem Code</button></form><div data-access-message hidden></div></div></section>
  <section class="promo26-active-access"><div class="promo26-section-heading"><div><p class="eyebrow">Your Access</p><h2>${access.staffBypass?"Administrative Preview":"Active entitlements"}</h2></div><span>${access.features.size} / ${C.FEATURES.length} unlocked</span></div><div class="promo26-entitlement-list">${access.redemptions.map((row)=>`<article class="promo26-entitlement"><div><strong>${C.safe(row.code||row.promoId||"Promotional Code")}</strong><small>${C.safe(expiryText(row))}</small></div><div class="promo26-feature-pills">${(row.featureIds||[]).map((id)=>`<span>${C.safe(C.FEATURE_BY_ID.get(id)?.short||C.humanize(id))}</span>`).join("")}</div></article>`).join("")}${access.grants.map((row)=>`<article class="promo26-entitlement"><div><strong>${C.safe(row.label||"Direct Promotional Grant")}</strong><small>${C.safe(expiryText(row))}</small></div><div class="promo26-feature-pills">${(row.featureIds||[]).map((id)=>`<span>${C.safe(C.FEATURE_BY_ID.get(id)?.short||C.humanize(id))}</span>`).join("")}</div></article>`).join("")}${!access.redemptions.length&&!access.grants.length&&!access.staffBypass?C.notice("You do not currently have an active promotional entitlement."):""}${access.staffBypass?C.notice("Administrators and Owners receive preview access to promotional product features. This does not alter Firestore record permissions."):""}</div></section>
  <section class="promo26-feature-section"><div class="promo26-section-heading"><div><p class="eyebrow">Feature Catalog</p><h2>Promotional features</h2></div></div><div class="promo26-feature-grid">${C.FEATURES.map((feature)=>{const unlocked=access.features.has(feature.id);return `<article class="promo26-feature-card is-${unlocked?"unlocked":"locked"}"><div class="promo26-feature-top"><span class="promo26-mini-badge">${C.safe(feature.badge)}</span><span class="promo26-status is-${unlocked?"unlocked":"locked"}">${unlocked?"Unlocked":"🔒 Locked"}</span></div><h3>${C.safe(feature.name)}</h3><p>${C.safe(feature.description)}</p><div class="hero-actions">${C.buttonLink(feature.route,unlocked?"Open Feature":"View Locked Feature",unlocked)}</div></article>`;}).join("")}</div></section>`;
  C.root.querySelector("[data-access-redeem]").addEventListener("submit",async(event)=>{
    event.preventDefault();const form=event.currentTarget,button=form.querySelector("button"),message=C.root.querySelector("[data-access-message]");
    try{C.setBusy(button,true,"Checking…","Redeem Code");const result=await C.redeemCode(new FormData(form).get("code"));C.setMessage(message,`Code redeemed. ${result.redemption.featureIds.length} feature${result.redemption.featureIds.length===1?"":"s"} unlocked.`,"success");setTimeout(()=>C.scheduleSync(true),300);}catch(error){C.setMessage(message,error?.message||"The code could not be redeemed.","error");}finally{C.setBusy(button,false,"Checking…","Redeem Code");}
  });
}

function promoForm(edit=null){
  const selected=edit?.featureIds||[]; const roles=edit?.eligibleRoles||ROLES;
  return `<form class="promo26-promo-form form-stack" data-promo-form><input type="hidden" name="editId" value="${C.safe(edit?.id||"")}"><input type="hidden" name="existingStatus" value="${C.safe(edit?.status||"active")}"><div class="panel-header"><div><p class="eyebrow">${edit?"Edit Campaign":"New Campaign"}</p><h2>${edit?C.safe(edit.code):"Create Promotional Code"}</h2></div>${edit?"":`<button class="button button-light" type="button" data-generate-code>Generate Code</button>`}</div><div data-promo-form-message hidden></div>
  <div class="form-row"><label>Campaign Name<input name="campaignName" maxlength="100" value="${C.safe(edit?.campaignName||"")}" required></label><label>Promotional Code<input name="code" maxlength="40" value="${C.safe(edit?.code||"")}" ${edit?"readonly":""} placeholder="COGNITUS2026" required></label></div>
  <label>Description<textarea name="description" maxlength="1000" rows="3">${C.safe(edit?.description||"")}</textarea></label>
  ${edit?"":`<div class="form-row"><label>Bulk Quantity<input name="quantity" type="number" min="1" max="100" value="1"><small>Create up to 100 unique codes at once.</small></label><label>Generated Prefix<input name="prefix" maxlength="12" value="COG"></label></div>`}
  <div class="form-row"><label>Starts At<input name="startsAt" type="datetime-local" value="${C.safe(C.toDatetimeLocal(edit?.startsAt))}"></label><label>Redeem Until<input name="redeemUntil" type="datetime-local" value="${C.safe(C.toDatetimeLocal(edit?.redeemUntil))}"></label></div>
  <div class="form-row"><label>Total Redemption Limit<input name="maxTotalRedemptions" type="number" min="0" max="100000" value="${Number(edit?.maxTotalRedemptions??100)}"><small>0 = unlimited</small></label><label>Per-Account Limit<input name="maxPerAccount" type="number" min="1" max="100" value="${Number(edit?.maxPerAccount??1)}"></label></div>
  <div class="form-row"><label>Access Mode<select name="accessMode"><option value="permanent" ${edit?.accessMode==="permanent"?"selected":""}>Permanent until revoked</option><option value="duration" ${!edit||edit.accessMode==="duration"?"selected":""}>Duration after redemption</option><option value="fixed_end" ${edit?.accessMode==="fixed_end"?"selected":""}>Fixed access end</option></select></label><label>Duration Hours<input name="accessDurationHours" type="number" min="1" max="43800" value="${Math.max(1,Math.round(Number(edit?.accessDurationSeconds||604800)/3600))}"></label></div>
  <div class="form-row"><label>Fixed Access End<input name="accessEndsAt" type="datetime-local" value="${C.safe(C.toDatetimeLocal(edit?.accessEndsAt))}"></label><label>When Redemption Window Ends<select name="campaignExpiryBehavior"><option value="preserve_access" ${edit?.campaignExpiryBehavior!=="revoke_on_campaign_end"?"selected":""}>Stop new redemptions only</option><option value="revoke_on_campaign_end" ${edit?.campaignExpiryBehavior==="revoke_on_campaign_end"?"selected":""}>End granted access too</option></select></label></div>
  <div class="form-row"><label>Eligible Organization ID<input name="eligibleOrganizationId" maxlength="128" value="${C.safe(edit?.eligibleOrganizationId||"")}" placeholder="Blank = any"></label><label>Distribution<select name="distribution"><option value="secret" ${edit?.distribution!=="campaign"?"selected":""}>Secret / manual</option><option value="campaign" ${edit?.distribution==="campaign"?"selected":""}>Public campaign</option></select></label></div>
  <fieldset class="promo26-fieldset"><legend>Eligible Roles</legend><div class="promo26-check-grid roles">${roleChecks(roles)}</div></fieldset><fieldset class="promo26-fieldset"><legend>Unlocks</legend><div class="promo26-check-grid">${featureChecks(selected)}</div></fieldset><button class="button button-dark" type="submit">${edit?"Save Campaign":"Create Promotional Code"}</button></form>`;
}
function grantForm(){
  return `<form class="form-stack" data-grant-form><p class="eyebrow">Direct Access</p><h2>Grant access without a code</h2><div data-grant-message hidden></div><div class="form-row"><label>User UID<input name="uid" maxlength="128" required></label><label>Label<input name="label" maxlength="80" value="Direct Promotional Grant"></label></div><label>Expires At<input name="expiresAt" type="datetime-local"><small>Leave blank for permanent access until revoked.</small></label><label>Administrative Note<textarea name="note" maxlength="500" rows="3"></textarea></label><fieldset class="promo26-fieldset"><legend>Features</legend><div class="promo26-check-grid">${featureChecks([])}</div></fieldset><button class="button button-dark" type="submit">Grant Access</button></form>`;
}
function adminCard(promo){
  const count=Number(promo.redeemedCount||0),max=Number(promo.maxTotalRedemptions||0);
  return `<article class="promo26-admin-card" data-promo-card="${C.safe(promo.id)}"><div class="promo26-admin-card-top"><div><span>${C.safe(promo.campaignName||"Promotion")}</span><h3>${C.safe(promo.code||promo.id)}</h3></div><span class="promo26-status-chip is-${C.safe(promo.status||"paused")}">${C.safe(C.humanize(promo.status||"paused"))}</span></div><p>${C.safe(promo.description||"No campaign description.")}</p><div class="promo26-admin-stats"><span><strong>${count}${max?` / ${max}`:""}</strong> redemptions</span><span><strong>${Number(promo.maxPerAccount||1)}</strong> per account</span><span><strong>${C.safe(C.humanize(promo.accessMode||"duration"))}</strong> access</span></div><div class="promo26-feature-pills">${(promo.featureIds||[]).map((id)=>`<span>${C.safe(C.FEATURE_BY_ID.get(id)?.short||C.humanize(id))}</span>`).join("")}</div><div class="hero-actions"><button class="button button-light" data-edit-promo="${C.safe(promo.id)}">Edit</button>${promo.status==="active"?`<button class="button button-light" data-status-promo="${C.safe(promo.id)}" data-status="paused">Pause</button>`:`<button class="button button-light" data-status-promo="${C.safe(promo.id)}" data-status="active">Activate</button>`}<button class="button button-light" data-status-promo="${C.safe(promo.id)}" data-status="revoked">Revoke Code</button><button class="button button-light" data-revoke-redemptions="${C.safe(promo.id)}">Revoke Existing Access</button><button class="button button-light" data-view-redemptions="${C.safe(promo.id)}">Redemptions</button>${C.isOwner()&&count===0?`<button class="button button-light" data-delete-promo="${C.safe(promo.id)}">Delete</button>`:""}</div><div data-redemption-detail="${C.safe(promo.id)}" hidden></div></article>`;
}

async function savePromoForm(form){
  const data=C.formObject(form),message=form.querySelector("[data-promo-form-message]"),button=form.querySelector('button[type="submit"]');
  const features=C.selectedValues(form,"featureIds"),roles=C.selectedValues(form,"eligibleRoles");
  if(!features.length)return C.setMessage(message,"Select at least one feature.","error");
  if(!roles.length)return C.setMessage(message,"Select at least one eligible role.","error");
  const editId=C.clean(data.editId),base=C.normalizePromoCode(data.code); if(base.length<4)return C.setMessage(message,"Codes must be at least four characters.","error");
  const quantity=editId?1:Math.min(100,Math.max(1,Number(data.quantity||1))); const mode=["permanent","duration","fixed_end"].includes(data.accessMode)?data.accessMode:"duration";
  const startsAt=C.toTimestampFromInput(data.startsAt),redeemUntil=C.toTimestampFromInput(data.redeemUntil),accessEndsAt=C.toTimestampFromInput(data.accessEndsAt); if(mode==="fixed_end"&&!accessEndsAt)return C.setMessage(message,"Choose a fixed access end.","error");
  const codes=editId?[editId]:Array.from({length:quantity},(_,index)=>quantity===1?base:C.randomCode(data.prefix||base.split("-")[0]||"COG"));
  try{
    C.setBusy(button,true,"Saving…",editId?"Save Campaign":"Create Promotional Code");
    for(let index=0;index<codes.length;index++){
      const code=codes[index],ref=C.Fire.doc(C.db,"promotionalCodes",code);
      if(!editId && (await C.Fire.getDoc(ref)).exists())throw new Error(`Code ${code} already exists.`);
      const payload={id:code,code,campaignName:`${C.clean(data.campaignName).slice(0,100)}${quantity>1?` ${index+1}`:""}`,description:C.clean(data.description).slice(0,1000),status:editId&&["active","paused","revoked"].includes(data.existingStatus)?data.existingStatus:"active",startsAt,redeemUntil,maxTotalRedemptions:Math.max(0,Math.min(100000,Number(data.maxTotalRedemptions||0))),maxPerAccount:Math.max(1,Math.min(100,Number(data.maxPerAccount||1))),accessMode:mode,accessDurationSeconds:Math.max(3600,Math.min(157680000,Number(data.accessDurationHours||168)*3600)),accessEndsAt,campaignExpiryBehavior:data.campaignExpiryBehavior==="revoke_on_campaign_end"?"revoke_on_campaign_end":"preserve_access",featureIds:features,eligibleRoles:roles,eligibleOrganizationId:C.clean(data.eligibleOrganizationId)||null,distribution:data.distribution==="campaign"?"campaign":"secret",updatedAt:C.Fire.serverTimestamp()};
      if(editId)await C.Fire.updateDoc(ref,payload); else await C.Fire.setDoc(ref,{...payload,redeemedCount:0,createdByUid:C.authUser.uid,createdAt:C.Fire.serverTimestamp()});
    }
    await C.writePromoAudit(editId?"PROMO_UPDATED":"PROMO_CREATED",editId||codes[0],editId?`Updated promotional code ${editId}.`:`Created ${codes.length} promotional code(s).`,{quantity:codes.length,featureCount:features.length});
    C.setMessage(message,editId?"Campaign updated.":`${codes.length} code${codes.length===1?"":"s"} created.`,"success"); setTimeout(()=>C.scheduleSync(true),300);
  }catch(error){C.setMessage(message,error?.message||"The promotional code could not be saved.","error");}finally{C.setBusy(button,false,"Saving…",editId?"Save Campaign":"Create Promotional Code");}
}

function bindAdmin(promos,grants){
  C.root.querySelectorAll("[data-admin-tab]").forEach((button)=>button.addEventListener("click",()=>{C.root.querySelectorAll("[data-admin-panel]").forEach((panel)=>panel.hidden=panel.dataset.adminPanel!==button.dataset.adminTab);C.root.querySelectorAll("[data-admin-tab]").forEach((item)=>item.className=`button ${item===button?"button-dark":"button-light"}`);}));
  const bindForm=()=>{const form=C.root.querySelector("[data-promo-form]");form?.querySelector("[data-generate-code]")?.addEventListener("click",()=>form.elements.code.value=C.randomCode(form.elements.prefix?.value||"COG"));form?.addEventListener("submit",(event)=>{event.preventDefault();savePromoForm(form);});}; bindForm();
  C.root.querySelectorAll("[data-edit-promo]").forEach((button)=>button.addEventListener("click",()=>{const promo=promos.find((item)=>item.id===button.dataset.editPromo);const panel=C.root.querySelector('[data-admin-panel="create"]');panel.innerHTML=promoForm(promo);panel.hidden=false;C.root.querySelector('[data-admin-panel="campaigns"]').hidden=true;bindForm();panel.scrollIntoView({behavior:"smooth",block:"start"});}));
  C.root.querySelectorAll("[data-status-promo]").forEach((button)=>button.addEventListener("click",async()=>{await C.Fire.updateDoc(C.Fire.doc(C.db,"promotionalCodes",button.dataset.statusPromo),{status:button.dataset.status,updatedAt:C.Fire.serverTimestamp()});await C.writePromoAudit("PROMO_STATUS_CHANGED",button.dataset.statusPromo,`Promotion status changed to ${button.dataset.status}.`,{status:button.dataset.status});C.scheduleSync(true);}));
  C.root.querySelectorAll("[data-view-redemptions]").forEach((button)=>button.addEventListener("click",async()=>{const detail=C.root.querySelector(`[data-redemption-detail="${CSS.escape(button.dataset.viewRedemptions)}"]`);if(!detail)return;if(!detail.hidden){detail.hidden=true;return;}detail.hidden=false;detail.innerHTML="<p>Loading…</p>";const rows=await C.readWhere("promoRedemptions","promoId","==",button.dataset.viewRedemptions,1000);detail.innerHTML=rows.length?`<div class="promo26-redemption-table">${rows.sort((a,b)=>C.timestampMs(b.lastRedeemedAt)-C.timestampMs(a.lastRedeemedAt)).map((row)=>`<article><strong>${C.safe(row.userCognitusId||row.uid)}</strong><span>${Number(row.redemptionCount||1)} use${Number(row.redemptionCount||1)===1?"":"s"}</span><small>${C.safe(C.humanize(row.status||"active"))} · ${C.safe(C.formatTimestamp(row.lastRedeemedAt))}</small></article>`).join("")}</div>`:C.notice("No redemptions yet.");}));
  C.root.querySelectorAll("[data-revoke-redemptions]").forEach((button)=>button.addEventListener("click",async()=>{if(!confirm("Revoke all existing access granted by this code?"))return;const rows=await C.readWhere("promoRedemptions","promoId","==",button.dataset.revokeRedemptions,1000);for(let i=0;i<rows.length;i+=400){const batch=C.Fire.writeBatch(C.db);rows.slice(i,i+400).forEach((row)=>batch.update(C.Fire.doc(C.db,"promoRedemptions",row.id),{status:"revoked",updatedAt:C.Fire.serverTimestamp()}));await batch.commit();}await C.writePromoAudit("PROMO_ACCESS_REVOKED",button.dataset.revokeRedemptions,`Revoked ${rows.length} redemption record(s).`,{count:rows.length});C.scheduleSync(true);}));
  C.root.querySelectorAll("[data-delete-promo]").forEach((button)=>button.addEventListener("click",async()=>{if(!confirm("Delete this unused promotional code?"))return;await C.Fire.deleteDoc(C.Fire.doc(C.db,"promotionalCodes",button.dataset.deletePromo));C.scheduleSync(true);}));
  const grant=C.root.querySelector("[data-grant-form]");grant?.addEventListener("submit",async(event)=>{event.preventDefault();const data=C.formObject(grant),features=C.selectedValues(grant,"featureIds"),message=grant.querySelector("[data-grant-message]");if(!features.length)return C.setMessage(message,"Select at least one feature.","error");const target=await C.readDoc("users",C.clean(data.uid)).catch(()=>null);if(!target)return C.setMessage(message,"No Cognitus user exists with that UID.","error");try{const ref=C.Fire.doc(C.Fire.collection(C.db,"promoAccessGrants"));await C.Fire.setDoc(ref,{id:ref.id,uid:target.id,userCognitusId:target.cognitusId||"",featureIds:features,status:"active",source:"manual_grant",label:C.clean(data.label).slice(0,80)||"Direct Promotional Grant",note:C.clean(data.note).slice(0,500),expiresAt:C.toTimestampFromInput(data.expiresAt),grantedByUid:C.authUser.uid,createdAt:C.Fire.serverTimestamp(),updatedAt:C.Fire.serverTimestamp()});await C.writePromoAudit("PROMO_DIRECT_GRANT",ref.id,`Granted Promotional Access to ${target.cognitusId||target.id}.`,{uid:target.id,featureCount:features.length});C.setMessage(message,"Direct access granted.","success");setTimeout(()=>C.scheduleSync(true),300);}catch(error){C.setMessage(message,error?.message||"Direct access could not be granted.","error");}});
  C.root.querySelectorAll("[data-revoke-grant]").forEach((button)=>button.addEventListener("click",async()=>{await C.Fire.updateDoc(C.Fire.doc(C.db,"promoAccessGrants",button.dataset.revokeGrant),{status:"revoked",updatedAt:C.Fire.serverTimestamp()});C.scheduleSync(true);}));
}

export async function renderPromoAdmin(){
  C.setTitle("Promotional Access Administration");
  if(!C.isAdmin()){C.root.innerHTML=`<section class="hero" data-promo-v26-page><p class="eyebrow">Access Denied</p><h1>Admin access required.</h1><p>Promotional campaign administration is restricted to active Cognitus Admins and Owners.</p></section>`;return;}
  const [promos,grants]=await Promise.all([C.readCollection("promotionalCodes",500),C.readCollection("promoAccessGrants",500)]);promos.sort((a,b)=>C.timestampMs(b.createdAt)-C.timestampMs(a.createdAt));grants.sort((a,b)=>C.timestampMs(b.createdAt)-C.timestampMs(a.createdAt));
  C.root.innerHTML=`<section class="promo26-admin-hero" data-promo-v26-page><p class="eyebrow">Administration</p><h1>Promotional Access Control</h1><p>Create campaign codes, control redemption windows and limits, choose exactly what each code unlocks, revoke access, and issue direct entitlements.</p></section><section class="promo26-admin-tabs"><button class="button button-dark" data-admin-tab="campaigns">Campaigns</button><button class="button button-light" data-admin-tab="create">Create</button><button class="button button-light" data-admin-tab="grants">Direct Grants</button></section><section class="promo26-feature-section" data-admin-panel="campaigns"><div class="promo26-section-heading"><div><p class="eyebrow">Campaigns</p><h2>${promos.length} promotional code${promos.length===1?"":"s"}</h2></div></div><div class="promo26-admin-list">${promos.length?promos.map(adminCard).join(""):C.notice("No promotional codes have been created.")}</div></section><section class="promo26-feature-section" data-admin-panel="create" hidden>${promoForm()}</section><section class="promo26-feature-section" data-admin-panel="grants" hidden>${grantForm()}<hr><div class="promo26-admin-list">${grants.length?grants.map((grant)=>`<article class="promo26-admin-card"><div class="promo26-admin-card-top"><div><span>${C.safe(grant.userCognitusId||grant.uid)}</span><h3>${C.safe(grant.label||"Direct Promotional Grant")}</h3></div><span class="promo26-status-chip is-${C.safe(grant.status||"revoked")}">${C.safe(C.humanize(grant.status||"revoked"))}</span></div><div class="promo26-feature-pills">${(grant.featureIds||[]).map((id)=>`<span>${C.safe(C.FEATURE_BY_ID.get(id)?.short||C.humanize(id))}</span>`).join("")}</div>${grant.status==="active"?`<button class="button button-light" data-revoke-grant="${C.safe(grant.id)}">Revoke</button>`:""}</article>`).join(""):C.notice("No direct promotional grants.")}</div></section>`;
  bindAdmin(promos,grants);
}
