import { FIREBASE_CDN_BASE, initializeFirebaseServices } from "./firebase/firebaseApp.js";
import { OWNER_BOOTSTRAP } from "./config/bootstrapConfig.js";

const root = document.querySelector("#page-root");
const nav = document.querySelector(".topnav");
let auth = null;
let db = null;
let A = null;
let F = null;
let authUser = null;
let userRecord = null;

const reasons = ["Hiring Review", "Promotion Review", "Partnership Review", "Internal Investigation", "Safety Concern", "Appeal/Correction Review", "Other"];

function clean(v){return String(v || "").trim();}
function discordId(v){return clean(v).replace(/\D/g, "");}
function emailFor(id){return `${discordId(id)}@cognitus.local`;}
function id(prefix){return `${prefix}-${new Date().getFullYear()}-${Math.random().toString(36).slice(2,8).toUpperCase()}`;}
function route(){return (location.hash.replace("#","").split("?")[0] || "/");}
function qs(){return new URLSearchParams((location.hash.split("?")[1] || ""));}
function setTitle(t){document.title = `${t} · Cognitus Solutions`;}
function esc(s){return String(s ?? "").replace(/[&<>'"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;","\"":"&quot;"}[m]));}
function fmt(ts){return ts?.toDate?.()?.toLocaleString?.() || ts || "—";}
function msg(text){return `<div class="notice">${esc(text)}</div>`;}
function btn(h,l,c="button-light"){return `<a class="button ${c}" href="${h}">${l}</a>`;}
function hero(k,t,p,actions=""){root.innerHTML=`<section class="hero hero-wide"><p class="eyebrow">${k}</p><h1>${t}</h1><p>${p}</p><div class="hero-actions">${actions}</div></section>`;}
function field(label,name,type="text",extra=""){return `<label>${label}<input name="${name}" type="${type}" ${extra}></label>`;}
function textarea(label,name,extra=""){return `<label>${label}<textarea name="${name}" rows="5" ${extra}></textarea></label>`;}
function formData(form){return Object.fromEntries(new FormData(form).entries());}
async function mods(){if(A&&F)return; const services=await initializeFirebaseServices(); auth=services.auth; db=services.db; A=await import(`${FIREBASE_CDN_BASE}/firebase-auth.js`); F=await import(`${FIREBASE_CDN_BASE}/firebase-firestore.js`);}
async function getDoc(path,idv){const s=await F.getDoc(F.doc(db,path,idv)); return s.exists()?{id:s.id,...s.data()}:null;}
async function current(){if(!authUser)return null; userRecord=await getDoc("users",authUser.uid); if(userRecord) await ensureProfile(); return userRecord;}
function requireLogin(){if(userRecord)return false; hero("Login Required","You need to log in.","Create or access your Cognitus account first.",btn("#/login","Login","button-dark")+btn("#/register","Create Account")); return true;}
function canReview(){return ["reviewer","admin","owner"].includes(userRecord?.role);} function canAdmin(){return ["admin","owner"].includes(userRecord?.role);} function isOwner(){return userRecord?.role==="owner";}
async function ensureProfile(){if(!authUser||!userRecord)return; const existing=await getDoc("profiles",authUser.uid); if(existing)return existing; const now=F.serverTimestamp(); const profile={id:authUser.uid,cognitusId:id("PRF"),linkedUserId:authUser.uid,type:"person",displayName:userRecord.displayName||userRecord.discordUsername||"User",robloxUsernames:userRecord.robloxUsername?[userRecord.robloxUsername]:[],discordUsernames:[userRecord.discordUsername||userRecord.displayName||""].filter(Boolean),discordIds:[userRecord.discordId].filter(Boolean),knownAliases:[],claimedByUid:authUser.uid,identityStatus:"self_registered",identityConfidence:100,professionalStanding:"unreviewed",riskLevel:"unreviewed",reportCount:0,appealCount:0,createdAt:now,updatedAt:now}; await F.setDoc(F.doc(db,"profiles",authUser.uid),profile,{merge:true}); return profile;}

function renderNav(){const u=userRecord; if(!u){nav.innerHTML=`<a href="#/">Home</a><a href="#/features">Features</a><a href="#/login">Login</a><a class="button button-dark" href="#/register">Create Account</a>`; return;} nav.innerHTML=`<a href="#/">Home</a><a href="#/dashboard">Dashboard</a><a href="#/search">Run Check</a><a href="#/reports/submit">Report/Comment</a><a href="#/history">History</a><a href="#/claims">Claims</a><a href="#/appeals">Appeals</a>${canReview()?`<a href="#/review">Review</a>`:""}${canAdmin()?`<a href="#/admin">Manage</a>`:""}${isOwner()?`<a href="#/owner">Owner</a>`:""}<a href="#/owner-bootstrap">Bootstrap</a><button id="nav-logout" class="button button-light" type="button">Logout</button><span class="nav-user">${esc(u.displayName)} · ${esc(u.role)}</span>`; document.querySelector("#nav-logout")?.addEventListener("click",async()=>{await A.signOut(auth); location.hash="#/login";});}
function footer(){let el=document.querySelector(".site-footer"); if(!el){el=document.createElement("footer"); el.className="site-footer"; document.querySelector("#app").appendChild(el);} el.innerHTML=`<span>Cognitus Solutions</span><a href="#/terms">Terms</a><a href="#/privacy">Privacy</a><a href="#/about">About</a>`;}

function home(){setTitle("Home"); hero("Cognitus Solutions","Professional screening for Roblox and Discord communities.","Search people and organizations, log checks with reasons, and submit reports/comments for review.", userRecord?btn("#/dashboard","Dashboard","button-dark")+btn("#/search","Run Check"):btn("#/register","Create Account","button-dark")+btn("#/login","Login"));}
function simple(k,t,p){setTitle(t); hero(k,t,p,btn("#/dashboard","Back to Dashboard","button-dark"));}

function login(){setTitle("Login"); root.innerHTML=`<section class="form-card"><p class="eyebrow">Login</p><h1>Account access</h1><div id="m"></div><form id="f" class="form-stack">${field("Discord ID","discordId","text","required")}${field("Password","password","password","required")}<label class="checkbox-line"><input name="remember" type="checkbox" checked> Remember Me</label><button type="submit">Login</button><a href="#/password-reset">Need a password reset?</a></form></section>`; document.querySelector("#f").onsubmit=async e=>{e.preventDefault(); const d=formData(e.target); try{await A.setPersistence(auth,d.remember?A.browserLocalPersistence:A.browserSessionPersistence); await A.signInWithEmailAndPassword(auth,emailFor(d.discordId),d.password); location.hash="#/dashboard";}catch(err){document.querySelector("#m").innerHTML=msg(err.message.includes("auth")?"The Discord ID or password is incorrect.":err.message);}};}
function register(){setTitle("Create Account"); root.innerHTML=`<section class="form-card"><p class="eyebrow">Create Account</p><h1>Join Cognitus</h1><div id="m"></div><form id="f" class="form-stack">${field("Discord Username","discordUsername","text","required placeholder='Executive_Eagle'")}${field("Discord ID","discordId","text","required")}${field("Password","password","password","required minlength='8'")}<label class="checkbox-line"><input name="remember" type="checkbox" checked> Remember Me</label><button type="submit">Create Account</button></form></section>`; document.querySelector("#f").onsubmit=async e=>{e.preventDefault(); const d=formData(e.target); const did=discordId(d.discordId); try{await A.setPersistence(auth,d.remember?A.browserLocalPersistence:A.browserSessionPersistence); const cred=await A.createUserWithEmailAndPassword(auth,emailFor(did),d.password); await A.updateProfile(cred.user,{displayName:clean(d.discordUsername)}); const now=F.serverTimestamp(); const user={uid:cred.user.uid,cognitusId:id("USR"),profileId:cred.user.uid,displayName:clean(d.discordUsername),discordUsername:clean(d.discordUsername),discordId:did,role:"user",status:"active",accountType:"individual",organizationId:null,syntheticEmail:emailFor(did),realEmailCollected:false,createdAt:now,updatedAt:now,lastLoginAt:now}; const profile={id:cred.user.uid,cognitusId:id("PRF"),linkedUserId:cred.user.uid,type:"person",displayName:user.displayName,robloxUsernames:[],discordUsernames:[user.discordUsername],discordIds:[did],knownAliases:[],claimedByUid:cred.user.uid,identityStatus:"self_registered",identityConfidence:100,professionalStanding:"unreviewed",riskLevel:"unreviewed",reportCount:0,appealCount:0,createdAt:now,updatedAt:now}; const batch=F.writeBatch(db); batch.set(F.doc(db,"users",cred.user.uid),user); batch.set(F.doc(db,"profiles",cred.user.uid),profile); await batch.commit(); location.hash="#/dashboard";}catch(err){document.querySelector("#m").innerHTML=msg(err.message);}};}

async function dashboard(){setTitle("Dashboard"); if(requireLogin())return; await ensureProfile(); root.innerHTML=`<section class="dashboard-hero"><div><p class="eyebrow">Dashboard</p><h1>Welcome, ${esc(userRecord.displayName)}.</h1><p>Your profile is searchable by Discord username and Discord ID.</p></div><div class="account-card"><span>Cognitus ID</span><strong>${esc(userRecord.cognitusId)}</strong><small>${esc(userRecord.role)} · ${esc(userRecord.discordId)}</small></div></section><section class="quick-actions">${btn("#/search","Run Check","button-dark")}${btn("#/reports/submit","Report/Comment")}${btn("#/history","Check History")}${btn("#/claims","Claim Profile")}${btn("#/appeals","Appeals")}${canReview()?btn("#/review","Review Queue"):""}${canAdmin()?btn("#/admin","Admin"):""}${isOwner()?btn("#/owner","Owner"):""}</section><section class="stats-grid"><article class="stat-card"><span>Status</span><strong>${esc(userRecord.status)}</strong><small>Account status</small></article><article class="stat-card"><span>Role</span><strong>${esc(userRecord.role)}</strong><small>Access level</small></article><article class="stat-card"><span>Profile</span><strong>Active</strong><small>Searchable record exists</small></article></section>`;}

async function searchProfiles(type,field,value){const v=clean(value); if(!v)return[]; if(type==="Organization"){const s=await F.getDocs(F.query(F.collection(db,"organizations"),F.limit(50))); return s.docs.map(x=>({id:x.id,...x.data()})).filter(o=>clean(o.name).toLowerCase().includes(v.toLowerCase()));} let qfield=field==="Discord ID"?"discordIds":field==="Discord Username"?"discordUsernames":"robloxUsernames"; let qval=field==="Discord ID"?discordId(v):v; const snap=await F.getDocs(F.query(F.collection(db,"profiles"),F.where(qfield,"array-contains",qval),F.limit(25))); return snap.docs.map(x=>({id:x.id,...x.data()}));}
async function runCheckPage(){setTitle("Run Check"); if(requireLogin())return; await ensureProfile(); root.innerHTML=`<section class="hero hero-wide"><p class="eyebrow">Run Check</p><h1>Search people or organizations.</h1><p>Every check requires a reason and is permanently logged.</p></section><section class="search-layout"><form id="f" class="panel form-stack"><label>Search Type<select name="type"><option>Person</option><option>Organization</option></select></label><label>Search By<select name="field"><option>Discord Username</option><option>Discord ID</option><option>Roblox Username</option></select></label>${field("Search Query","query","text","required")}<label>Reason<select name="reason" required><option value="">Select reason</option>${reasons.map(r=>`<option>${r}</option>`).join("")}</select></label>${textarea("Notes","notes")}<button type="submit">Run Logged Check</button></form><aside class="panel"><p class="eyebrow">Results</p><div id="results">No check run yet.</div></aside></section>`; document.querySelector("#f").onsubmit=async e=>{e.preventDefault(); const d=formData(e.target); const box=document.querySelector("#results"); try{box.innerHTML="Searching..."; const results=await searchProfiles(d.type,d.field,d.query); const ref=F.doc(F.collection(db,"checkLogs")); await F.setDoc(ref,{id:ref.id,cognitusId:id("CHK"),checkedByUid:authUser.uid,checkedByCognitusId:userRecord.cognitusId,searchType:d.type,searchField:d.field,searchQuery:clean(d.query),reason:d.reason,additionalNotes:clean(d.notes),targetProfileId:d.type==="Person"?results[0]?.id||null:null,targetOrganizationId:d.type==="Organization"?results[0]?.id||null:null,resultSummary:results.length?`${results.length} result(s)`:"No matching records",createdAt:F.serverTimestamp(),updatedAt:F.serverTimestamp()}); box.innerHTML=`<p><strong>Check logged:</strong> ${ref.id}</p><div class="hero-actions">${btn(`#/reports/quick?checkId=${ref.id}`,"Quick Report")}${btn(`#/reports/full?checkId=${ref.id}`,"Full Report")}${btn(`#/reports/submit?target=${results[0]?.id||""}`,"Report/Comment")}</div>`+(results.length?results.map(r=>`<article class="result-card"><h3>${esc(r.displayName||r.name)}</h3><p>${esc(r.professionalStanding||r.verificationStatus||"unreviewed")}</p><div class="record-meta"><span>${esc(r.cognitusId)}</span><span>${esc(r.identityStatus||r.trustLevel||"unreviewed")}</span></div></article>`).join(""):msg("No matching records. New users are searchable after their profile exists."));}catch(err){box.innerHTML=msg(err.message);}};}

async function submitReportPage(){setTitle("Report/Comment"); if(requireLogin())return; const target=qs().get("target")||""; root.innerHTML=`<section class="form-card wide-form"><p class="eyebrow">Report / Comment</p><h1>Submit information about a person.</h1><div id="m"></div><form id="f" class="form-stack">${field("Target Profile ID","target","text",`value="${esc(target)}" placeholder="Profile document ID"`)}${field("Category","category","text","required placeholder='Misconduct, employment note, concern, positive recognition'")}${field("Severity","severity","text","value="+"Informational")} ${field("Summary","summary","text","required")}${textarea("Details / Comment","details","required")}<button type="submit">Submit for Review</button></form></section>`; document.querySelector("#f").onsubmit=async e=>{e.preventDefault(); const d=formData(e.target); try{const ref=F.doc(F.collection(db,"reports")); await F.setDoc(ref,{id:ref.id,cognitusId:id("RPT"),subjectProfileId:clean(d.target)||null,subjectOrganizationId:null,submittedByUid:authUser.uid,submittedByCognitusId:userRecord.cognitusId,category:clean(d.category),severity:clean(d.severity)||"Informational",summary:clean(d.summary),details:clean(d.details),status:"pending_review",visibility:"private_review",createdAt:F.serverTimestamp(),updatedAt:F.serverTimestamp()}); document.querySelector("#m").innerHTML=msg(`Submitted. Report ID: ${ref.id}`); e.target.reset();}catch(err){document.querySelector("#m").innerHTML=msg(err.message);}};}

async function history(){setTitle("History"); if(requireLogin())return; const snap=await F.getDocs(F.query(F.collection(db,"checkLogs"),F.where("checkedByUid","==",authUser.uid),F.limit(50))); const rows=snap.docs.map(d=>({id:d.id,...d.data()})); root.innerHTML=`<section class="hero hero-wide"><p class="eyebrow">History</p><h1>Check history</h1><p>Checks you have run.</p></section><section class="panel record-list">${rows.length?rows.map(c=>`<article class="record-row"><div><strong>${esc(c.searchQuery)}</strong><span>${esc(c.reason)} · ${esc(c.searchType)}</span><small>${fmt(c.createdAt)}</small></div><div class="mini-actions">${btn(`#/reports/quick?checkId=${c.id}`,"Quick")}${btn(`#/reports/full?checkId=${c.id}`,"Full")}</div></article>`).join(""):msg("No checks yet.")}</section>`;}
async function reportPage(mode){setTitle(mode==="full"?"Full Report":"Quick Report"); if(requireLogin())return; const checkId=qs().get("checkId"); const c=checkId?await getDoc("checkLogs",checkId):null; root.innerHTML=`<section class="report-document"><div class="report-header"><div><p class="eyebrow">${mode} report</p><h1>Cognitus Report</h1></div><div class="report-id-card"><span>Check</span><strong>${esc(checkId||"Missing")}</strong><small>${fmt(c?.createdAt)}</small></div></div>${c?`<section class="report-section"><h2>Search Summary</h2><dl class="report-dl"><dt>Query</dt><dd>${esc(c.searchQuery)}</dd><dt>Type</dt><dd>${esc(c.searchType)}</dd><dt>Field</dt><dd>${esc(c.searchField)}</dd><dt>Reason</dt><dd>${esc(c.reason)}</dd><dt>Result</dt><dd>${esc(c.resultSummary)}</dd></dl></section>${mode==="full"?`<section class="report-section"><h2>Notes</h2><p>${esc(c.additionalNotes||"No notes provided.")}</p></section>`:""}`:msg("Check record not found.")}<div class="report-toolbar no-print"><button class="button button-dark" onclick="window.print()">Print / Save PDF</button>${btn("#/history","Back to History")}</div></section>`;}

async function claims(){setTitle("Claims"); if(requireLogin())return; root.innerHTML=`<section class="form-card"><p class="eyebrow">Claims</p><h1>Claim a profile</h1><div id="m"></div><form id="f" class="form-stack">${field("Profile ID","profileId","text","required")}${textarea("Statement","statement")}<button type="submit">Submit Claim</button></form></section>`; document.querySelector("#f").onsubmit=async e=>{e.preventDefault(); const d=formData(e.target); try{await F.setDoc(F.doc(F.collection(db,"claims")),{cognitusId:id("CLM"),profileId:clean(d.profileId),submittedByUid:authUser.uid,submittedDiscordId:userRecord.discordId,statement:clean(d.statement),status:"pending_review",createdAt:F.serverTimestamp(),updatedAt:F.serverTimestamp()}); document.querySelector("#m").innerHTML=msg("Claim submitted.");}catch(err){document.querySelector("#m").innerHTML=msg(err.message);}};}
async function appeals(){setTitle("Appeals"); if(requireLogin())return; root.innerHTML=`<section class="form-card"><p class="eyebrow">Appeals</p><h1>Appeals & Corrections</h1><div id="m"></div><form id="f" class="form-stack">${field("Profile ID","profileId","text","required")}${field("Report ID","reportId","text","required")}${field("Reason","reason","text","required")}${textarea("Statement","statement","required")}<button type="submit">Submit Appeal</button></form></section>`; document.querySelector("#f").onsubmit=async e=>{e.preventDefault(); const d=formData(e.target); try{await F.setDoc(F.doc(F.collection(db,"appeals")),{cognitusId:id("APL"),profileId:clean(d.profileId),reportId:clean(d.reportId),reason:clean(d.reason),statement:clean(d.statement),submittedByUid:authUser.uid,status:"pending_review",createdAt:F.serverTimestamp(),updatedAt:F.serverTimestamp()}); document.querySelector("#m").innerHTML=msg("Appeal submitted.");}catch(err){document.querySelector("#m").innerHTML=msg(err.message);}};}
async function review(){setTitle("Review"); if(requireLogin())return; if(!canReview())return hero("Access Denied","Reviewer access required.","Only reviewers, admins, and owners can review records.",btn("#/dashboard","Dashboard")); const reps=await F.getDocs(F.query(F.collection(db,"reports"),F.where("status","==","pending_review"),F.limit(50))); root.innerHTML=`<section class="hero hero-wide"><p class="eyebrow">Review</p><h1>Pending reports/comments</h1><p>Reports awaiting review.</p></section><section class="panel record-list">${reps.docs.length?reps.docs.map(x=>{const r=x.data();return `<article class="record-row"><div><strong>${esc(r.summary)}</strong><span>${esc(r.category)} · ${esc(r.severity)}</span><small>${esc(r.details)}</small></div></article>`}).join(""):msg("No pending reports.")}</section>`;}
async function admin(){if(requireLogin())return; if(!canAdmin())return hero("Access Denied","Admin access required.","",btn("#/dashboard","Dashboard")); const users=await F.getDocs(F.query(F.collection(db,"users"),F.limit(50))); root.innerHTML=`<section class="hero hero-wide"><p class="eyebrow">Admin</p><h1>Users</h1><p>Registered accounts.</p></section><section class="panel record-list">${users.docs.map(x=>{const u=x.data();return `<article class="record-row"><div><strong>${esc(u.displayName)}</strong><span>${esc(u.discordId)} · ${esc(u.role)}</span><small>${esc(u.cognitusId)}</small></div></article>`}).join("")}</section>`;}
async function owner(){if(requireLogin())return; if(!isOwner())return hero("Access Denied","Owner access required.","",btn("#/dashboard","Dashboard")); hero("Owner","Owner command center.","Core owner account is active.",btn("#/admin","Admin","button-dark")+btn("#/review","Review"));}
async function bootstrap(){if(requireLogin())return; root.innerHTML=`<section class="hero"><p class="eyebrow">Owner Bootstrap</p><h1>Secure first-owner setup.</h1><div id="m"></div><button id="b" class="button button-dark">Run Owner Bootstrap</button></section>`; document.querySelector("#b").onclick=async()=>{try{if(userRecord.discordId!==OWNER_BOOTSTRAP.ownerDiscordId)throw new Error("This account is not the configured owner Discord ID."); await F.setDoc(F.doc(db,"users",authUser.uid),{role:"owner",status:"active",ownerBootstrap:true,updatedAt:F.serverTimestamp()},{merge:true}); await F.setDoc(F.doc(db,"settings","bootstrap"),{complete:true,completedBy:authUser.uid,completedByDiscordId:userRecord.discordId,ownerDiscordId:userRecord.discordId,completedAt:F.serverTimestamp()},{merge:true}); userRecord=await getDoc("users",authUser.uid); renderNav(); document.querySelector("#m").innerHTML=msg("Owner bootstrap complete.");}catch(err){document.querySelector("#m").innerHTML=msg(err.message);}};}

async function render(){await mods(); await current(); renderNav(); footer(); const r=route(); try{if(r==="/")return home(); if(r==="/features")return simple("Features","Features","Cognitus supports logged checks, searchable profiles, reports/comments, appeals, review queues, and owner controls."); if(r==="/about")return simple("About","About Cognitus","A Roblox and Discord employment intelligence portal."); if(r==="/terms")return simple("Terms","Terms","Use Cognitus professionally and only for legitimate review purposes."); if(r==="/privacy")return simple("Privacy","Privacy","Cognitus uses Discord IDs for login and does not collect real emails."); if(r==="/login")return login(); if(r==="/register")return register(); if(r==="/dashboard")return dashboard(); if(r==="/search")return runCheckPage(); if(r==="/reports/submit")return submitReportPage(); if(r==="/history")return history(); if(r==="/reports/quick")return reportPage("quick"); if(r==="/reports/full")return reportPage("full"); if(r==="/claims")return claims(); if(r==="/appeals")return appeals(); if(r==="/review")return review(); if(r==="/admin")return admin(); if(r==="/owner")return owner(); if(r==="/owner-bootstrap")return bootstrap(); if(r==="/password-reset")return simple("Password Reset","Request reset","Ask an owner/admin to reset your Cognitus password."); if(r==="/candidates")return simple("Candidates","Saved Candidates","Saved candidate tools will be restored after core records are stable."); if(r==="/organizations/saved")return simple("Organizations","Saved Organizations","Saved organization tools will be restored after core records are stable."); if(r==="/notifications")return simple("Notifications","Notifications","Notification tools will be restored after core records are stable."); hero("404","Page not found.","",btn("#/dashboard","Dashboard","button-dark"));}catch(err){hero("Error","This page could not load.",esc(err.message),btn("#/dashboard","Dashboard","button-dark"));}}

window.addEventListener("hashchange",render);
window.addEventListener("DOMContentLoaded",async()=>{await mods(); A.onAuthStateChanged(auth,async u=>{authUser=u; userRecord=u?await getDoc("users",u.uid):null; await render();});});
